# Generated by Django 6.0 on 2025-12-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_jobapplication_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('provider', 'Job Provider'), ('mentor', 'Mentor')], default='seeker', max_length=20),
        ),
    ]
