# Generated by Django 6.0 on 2025-12-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_job_provider_alter_jobapplication_seeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('provider', 'Job Provider'), ('mentor', 'Mentor')], max_length=20),
        ),
    ]
