# Generated by Django 6.0 on 2025-12-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_company_name_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('provider', 'Job Provider'), ('mentor', 'Mentor')], default='seeker', max_length=20),
        ),
    ]
