# Generated by Django 6.0.1 on 2026-02-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_experience_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='seeker',
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='seeker',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='MentorSession',
        ),
    ]
